use Kufer_Reporting

select

'A' as Adresstyp,
ADRnr,

iif(name is NULL, '', name) as name,
iif(vorname is NULL, '', vorname) as vorname, 	   
iif(zusatz1 is NULL, '', zusatz1) as zusatz, 	   
iif(ZUSATZ2 is NULL, '', ZUSATZ2) as ZUSATZ2, 	   
iif(ort is NULL, '', ort) as ort, 	   
iif(strasse is NULL,'',Replace(REPLACE(Strasse COLLATE Latin1_General_CS_AS, 'Str.', 'Straﬂe') COLLATE Latin1_General_CS_AS, 'str.', 'straﬂe')  ) as strasse,  
iif(Telefon is NULL, '', Telefon) as TEL_ANZEIGE, 	   
'' as TEL2_ANZEIGE,
iif(Fax is NULL, '', Fax) as FAX_ANZEIGE,
iif(EMail is NULL, '', EMail) as EMAIL_ANZEIGE,
'' as NOWERBUNG,
'' as nomailwerb,
'' as notelwerb,
iif(geschlecht is NULL, '', geschlecht) as geschlecht, 	   
iif(iif(gebdatadr is NULL, '30.12.1899', gebdatadr) = '30.12.1899', '',CONVERT(nvarchar(10),gebdatadr,20))  as GEBDAT,
'' as BANKBEZ,
'' as konto,
'' as blz,
'' as erm_grund,
'' as erm_ende,
'' as erm_proz,
'' as guthaben,
'' as kontoname,
'' as kz_text,
iif(BEARBEITER is NULL, '', BEARBEITER) as BEARBEITER, 	   
iif(NATION is NULL, '', NATION) as NATION, 	   
'' as BUNDESLAND,
iif(iif(BEARBDATUM is NULL, '30.12.1899', BEARBDATUM) = '30.12.1899', '',CONVERT(nvarchar(10),BEARBDATUM,20) + ' ' + CONVERT(nvarchar(10),BEARBDATUM,114))  as BEARBDATUM,
'' as RCHG_ADR_1,
'' as RCHG_ADR_2,
'' as RCHG_ADR_3,
'' as RCHG_ADR_4,
'' as RCHG_ADR_5,
'' as RCHG_ADR_6,
'' as RCHG_ADR_7,
iif(Anrede is NULL, '', Anrede) as Anrede, 	   
iif(Mobil is NULL, '', Mobil) as MOBIL_ANZEIGE, 	   
'' as FAX2_ANZEIGE,
'Infofeld wird manuell nachgepflegt!' as info, 	   
'' as eLearningPersonAktiv, 	   
'' as eLearningLogin, 	 
'' as BIC,
'' as IBAN,
iif(iif(ErstelltDatum is NULL, '30.12.1899', ErstelltDatum) = '30.12.1899', '',CONVERT(nvarchar(10),ErstelltDatum,20))  as ErstelltDatum,
iif(ErstelltVon is NULL, '', ErstelltVon) as ErstelltVon, 	   
'' as krit1dummy,
'' as krit2dummy,
'' as krit3dummy,
'' as krit4dummy,
'' as krit5dummy,
'' as krit6dummy,
'' as SozProjekt,
iif(Titel is NULL, '', Titel) as Name_Titel, 	   
'' as eLearningUserID, 	  
'' as eLearningVon,
'' as eLearningBis, 
iif(Newsl_Erlaubt is NULL, '', Newsl_Erlaubt) as Newsl_Erlaubt, 	   
iif(iif(Newsl_AnlDatum is NULL, '30.12.1899', Newsl_AnlDatum) = '30.12.1899', '',CONVERT(nvarchar(10),Newsl_AnlDatum,20))  as Newsl_AnlDatum, 
'' as abteilung,
'' as entsendvhs,
'' as anm_sperre,
'' as nofaxwerb,
'' as krit7dummy,
'' as krit8dummy,
'' as krit9,
'' as krit10,
'' as krit11,
'' as krit12,
'' as krit13,
'' as krit14,
'' as krit15,
'' as krit16,
'' as krit17,
'' as krit18,
'' as krit19,
'' as krit20,
'' as krit21,
'' as krit22,
'' as krit23,
'' as sap_angelegt,

'' as SCHULKEY,
'' as BERUF,
'' as SEITWANN,
'' as KONTOINH,
'' as INAKTIV,
'' as FINANZAMT,
'' as VERTRAG,
'' as INFO_INTERN,
'' as INDHONSATZ,
iif(ANSPRACHE is NULL, '', ANSPRACHE) as ANSPRACHE,
'' as eLearningEMailDatum,
'' as STEUERNR,
'' as Krit1Doz,

'' as Krit2Doz,
'' as Krit3Doz,
'' as Krit4Doz,
'' as Krit5Doz,
'' as Krit6Doz,
'' as Progheft,
'' as Internet,
'' as Anmkarte,
'' as mandant,

'' as krit7Doz,
'' as krit8Doz,

iif(AdrNr is NULL, '', AdrNr) as TNNummer,

iif(Stelle is NULL, '', Stelle) as Stelle,
iif(Typ is NULL, '', Typ) as Typ,
iif(sort is NULL, '', sort) as sort,
iif(zustmitarb is NULL, '', zustmitarb) as zustmitarb,
iif(iif(dse_unterschrieben_datum is NULL, '30.12.1899', dse_unterschrieben_datum) = '30.12.1899', '',CONVERT(nvarchar(10),dse_unterschrieben_datum,20))  as dse_unterschrieben_datum,
iif(dse_unterschrieben_bearbeiter is NULL, '', dse_unterschrieben_bearbeiter) as dse_unterschrieben_bearbeiter,
iif(dse_unterschrieben_weg is NULL, '', dse_unterschrieben_weg) as dse_unterschrieben_weg,
iif(iif(dse_widerrufen_datum is NULL, '30.12.1899', dse_widerrufen_datum) = '30.12.1899', '',CONVERT(nvarchar(10),dse_widerrufen_datum,20))  as dse_widerrufen_datum,
iif(dse_widerrufen_bearbeiter is NULL, '', dse_widerrufen_bearbeiter) as dse_widerrufen_bearbeiter,
iif(dse_widerrufen_weg is NULL, '', dse_widerrufen_weg) as dse_widerrufen_weg,
iif(id is NULL, '', id) as nr

from ADR_PERS where name <>'' 